import React from "react";
import type { Metadata } from "next";
import { Suspense } from "react";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function SearchLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Suspense fallback={<div>loading</div>}>
            {children}
        </Suspense>
    );
}
