import React from "react";
import type { Metadata } from "next";
import NavBar from "../ui/nav/nav";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function BlogLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            {children}
        </section>
    );
}
